repos:
  - repo: git@github.com:Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: web/public/assets/(admin|base|plugins)/.*|Brewfile.lock.json|web/composer.lock|.*/installed.json|.*/package-lock.json|web/symfony.lock
